// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package pgdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Author struct {
	ID   int64       `json:"id"`
	Name string      `json:"name"`
	Bio  pgtype.Text `json:"bio"`
}

type Book struct {
	ID       int64       `json:"id"`
	AuthorID int64       `json:"authorId"`
	Title    string      `json:"title"`
	Isbn     string      `json:"isbn"`
	Subject  pgtype.Text `json:"subject"`
}
